In [1]:
# Importa a biblioteca numpy e a atribui ao alias 'np'
import numpy as np 

In [5]:
# Criado um ndarray chamado altura_em_centimetros transformando a lista lista_de_alturas em um ndarray do numpy com a função np.array()
# Transformado em outro objeto altura_em_metros, com os valores de altura_em_centimetros convertidos para metros.

lista_de_centimetros = list(range(170, 190, 5))
altura_em_centimetros = np.array(lista_de_centimetros)
altura_em_metros = altura_em_centimetros / 100


In [6]:
# Lista de alturas em centímetros
lista_de_alturas_cm = list(range(170, 190, 5)) 

# Convertendo para ndarray
alturas_em_centimetros = np.array(lista_de_alturas_cm)  

# Convertendo para metros
alturas_em_metros = alturas_em_centimetros / 100  

# Lista de pesos em Kg
lista_pesos = [70, 75, 80, 85]

# Convertendo para ndarray
pesos = np.array(lista_pesos)  

# Calculando o IMC
imc = pesos / (alturas_em_metros ** 2)  

print(imc)

[24.22145329 24.48979592 24.69135802 24.83564646]


In [7]:
# Dados financeiros: custo fixo, dívida financeira, renda familiar
dados_financeiros = [[3000, 2500, 1000, 10000], [1000, 2500, 3000, 5000], [6000, 5500, 7000, 16000]]

# 1). Transforma a lista de listas em ndarray
nd_financeiros = np.array(dados_financeiros)

# 2). Transpõe o array para ter uma linha por indivíduo e uma coluna por informação
nd_financeiros = nd_financeiros.transpose()

# Imprime a segunda linha (dados do segundo indivíduo)
print("Segunda linha:", nd_financeiros[1])  

# Imprime a segunda coluna (dívida financeira de todos os indivíduos)
print("Segunda coluna:", nd_financeiros[:, 1])  

# 3). Calcula o endividamento total
endividamento_total = nd_financeiros[:, 0] + nd_financeiros[:, 1]  # custo fixo + dívida financeira

print("Endividamento total:", endividamento_total)

Segunda linha: [2500 2500 5500]
Segunda coluna: [1000 2500 3000 5000]
Endividamento total: [ 4000  5000  4000 15000]


In [8]:
# Lista dados_financeiros
dados_financeiros = [[3000, 2500, 1000, 10000], [1000, 2500, 3000, 5000], [6000, 5500, 7000, 16000]]

# 1) Transforma a lista em um ndarray
nd_financeiros = np.array(dados_financeiros)

# 2) Transpõe o array (opcional, dependendo de como você quer organizar os dados)
nd_financeiros = nd_financeiros.transpose() 

# 3) Calcula o endividamento total (custo fixo + dívida financeira)
endividamento_total = nd_financeiros[:, 0] + nd_financeiros[:, 1] 

# 4) Corrigindo um valor específico (exemplo: corrigindo o custo fixo do 3º indivíduo para 1200)
nd_financeiros[2, 0] = 1200  

# Imprimindo os resultados
print("ndarray:\n", nd_financeiros)
print("\nEndividamento total:", endividamento_total)

ndarray:
 [[ 3000  1000  6000]
 [ 2500  2500  5500]
 [ 1200  3000  7000]
 [10000  5000 16000]]

Endividamento total: [ 4000  5000  4000 15000]


In [9]:
# Definindo a semente para garantir resultados reproduzíveis
np.random.seed(1234)
# Gera o array poi
poi = np.random.poisson(3, 100)

# 1) Cria o objeto bool_zero
bool_zero = poi == 0  # Compara cada elemento de 'poi' com zero

# 2) Conta quantos valores zero existem
qtd_zeros = np.sum(bool_zero)  # Soma os valores True (1) no array bool_zero
print(f"Quantidade de zeros: {qtd_zeros}")

# 3) Cria a variável poi_nao_zero com indexação booleana
poi_nao_zero = poi[~bool_zero]  # Usa ~ para inverter o array bool_zero
# Alternativa: poi_nao_zero = poi[poi != 0]  # Seleciona elementos diretamente diferentes de zero

print("poi original:", poi)
print("poi_nao_zero:", poi_nao_zero)

Quantidade de zeros: 6
poi original: [3 3 6 2 4 5 4 4 2 0 3 3 2 8 2 3 3 3 0 4 4 2 6 6 0 3 4 3 5 2 1 3 2 2 3 2 4
 4 5 7 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 0 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4
 1 1 7 1 2 1 3 7 0 4 4 0 6 1 3 4 2 5 4 5 5 3 4 6 8 2]
poi_nao_zero: [3 3 6 2 4 5 4 4 2 3 3 2 8 2 3 3 3 4 4 2 6 6 3 4 3 5 2 1 3 2 2 3 2 4 4 5 7
 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4 1 1 7 1
 2 1 3 7 4 4 6 1 3 4 2 5 4 5 5 3 4 6 8 2]
